version: 2

builds:
  - env:
      - CGO_ENABLED=0
    binary: rc-nekot
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - '386'
    ignore:
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format_overrides:
    - goos: windows
      formats: ['zip']

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
