version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - '386'
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format_overrides:
    - goos: windows
      formats: ['zip']

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  prerelease: auto
  draft: false

homebrew_casks:
  - name: nekot 
    repository:
      owner: shawnmittal
      name: homebrew-shawnmittal
    homepage: https://github.com/shawnmittal/nekot
    directory: Casks
    conflicts:
      - formula: nekot
    commit_author:
      name: shawnmittal
    hooks:
      post:
        install: |
          if OS.mac?
            if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
              system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", "#{staged_path}/nekot"]
            end
          end
    skip_upload: auto
